default: &default
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  adapter: mysql2
  username: root
  password:
  host: localhost
  database: protospace-42452_development

test:
  <<: *default
  adapter: mysql2
  username: root
  password:
  host: localhost
  database: protospace-42452_test

production:
  <<: *default
  adapter: postgresql
  url: <%= ENV['DATABASE_URL'] %>



# default: &default
#   encoding: utf8
#   pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

# development:
#   <<: *default
#   adapter: mysql2
#   username: root
#   password:
#   host: localhost
#   database: protospace_42452_development

# test:
#   <<: *default
#   adapter: mysql2
#   username: root
#   password:
#   host: localhost
#   database: protospace_42452_test

# production:
#   <<: *default
#   adapter: postgresql
#   url: <%= ENV['DATABASE_URL'] %>